/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackSlideTime: typeof import('./src/components/backSlideTime.vue')['default']
    Cloud: typeof import('./src/components/Switch/Cloud.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
    DaySlide: typeof import('./src/components/daySlide.vue')['default']
    Eath: typeof import('./src/components/Switch/Eath.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Fps: typeof import('./src/components/Fps/index.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    Misty: typeof import('./src/components/Switch/Misty.vue')['default']
    Needle: typeof import('./src/components/needle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./src/components/Switch/Star.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
    Time: typeof import('./src/components/time.vue')['default']
  }
}
